### ISSUE TITLE
HUNSPELL is not defined on line 18328 of configure

### ISSUE THREAD

**Issue by sbguthery** [opencog/link-grammar#943] opened 2019-04-30 00:11 UTC
System is UBUNTU running on a Dell.

**Comment by linas** [comment] 2019-04-30 02:40
Hi Scott!
-- which version of link-grammar? In the latest version, line 18328 is a comment about corpus stats.  Did you perhaps rebuild the configure script?

-- There are no variables called "HUNSPELL" There are variables called "HUNSPELL_LIBS" and HUNSPELL_CFLAGS and more.  However, those will remain undefined unless you have hunspell installed on your system.

**Comment by sbguthery** [comment] 2019-04-30 16:32
If, say, Hunspell isn't installed then PKG_CHECK_MODULES([HUNSPELL],...) in configure.ac becomes
PKG_CHECK_MODULES(HUNSPELL,...) in configure and is undefined when configure is executed.

**Comment by linas** [comment] 2019-04-30 17:29
Um, as a general rule, you should not be running `configure.ac`.  If you do that, then you are considered a "developer", and get to figure out how to fix any bugs you find yourself.  Mostly I'm thinking you probably have an incomplete installation of autotools.  Make sure you have the "extras" package.

**Comment by linas** [comment] 2019-09-19 19:00
Closing; I can't reproduce; I don't have hunspell installed, and everything seems to work fine ...

**Closed by linas** 2019-09-19 19:00 UTC
