### ISSUE TITLE
./autogen.sh generates error

### ISSUE THREAD

**Issue by chris-hawley** [opencog/link-grammar#544] opened 2017-05-28 23:18 UTC
steps to reproduce
1. git clone https://github.com/opencog/link-grammar.git
2. cd link-grammar
3. ./autogen.sh

Every library is freshly installed through apt on ubuntu 16.04.2 
I did run run octool to get the base dependencies for opencog prior to running these commands.

**Comment by linas** [comment] 2017-06-06 06:32
What's the error? I run link-grammar on ubuntu xenial ... daily. It works for me.  

Perhaps you did this on one of those days when git was unstable?  Only the release versions are guaranteed to actually work, whereas what is in git might not compile, etc. Maybe try again today?  r use a release version?

**Comment by linas** [comment] 2017-06-06 06:33
I'm closing, as 8 days ago, the source was deep in the middle of a major revision. All bets are off; if it reproduces, please post the error.

**Closed by linas** 2017-06-06 06:33 UTC
