### ISSUE TITLE
Using with Python3. ImportError: No module named 'linkgrammar'

### ISSUE THREAD

**Issue by mnvx** [opencog/link-grammar#530] opened 2017-03-31 14:19 UTC
I has install link-grammar from archive, version 5.3.15 on Ubuntu 16.04.

My steps:
```
./configure
make
make check
sudo make install
sudo ldconfig
make installcheck

cd bindings/python3
make
sudo make install
```

Output after `sudo make install`:

```
$ sudo make install
make[1]: вход в каталог «/home/ubuntu/tmp/link-grammar-5.3.15/bindings/python3»
 /bin/mkdir -p '/linkgrammar'
 /bin/bash ../../libtool   --mode=install /usr/bin/install -c   _clinkgrammar.la '/linkgrammar'
libtool: warning: relinking '_clinkgrammar.la'
libtool: install: (cd /home/ubuntu/tmp/link-grammar-5.3.15/bindings/python3; /bin/bash "/home/ubuntu/tmp/link-grammar-5.3.15/libtool"  --silent --tag CXX --mode=relink g++ -g -O2 -O3 -Wall -std=c++11 -D_DEFAULT_SOURCE -version-info 8:15:3 -module -no-undefined -o _clinkgrammar.la -rpath /linkgrammar ../../bindings/python3/_clinkgrammar_la-lg_python_wrap.lo ../../link-grammar/liblink-grammar.la -laspell -lstdc++ )
libtool: install: /usr/bin/install -c .libs/_clinkgrammar.so.5.3.15T /linkgrammar/_clinkgrammar.so.5.3.15
libtool: install: (cd /linkgrammar && { ln -s -f _clinkgrammar.so.5.3.15 _clinkgrammar.so.5 || { rm -f _clinkgrammar.so.5 && ln -s _clinkgrammar.so.5.3.15 _clinkgrammar.so.5; }; })
libtool: install: (cd /linkgrammar && { ln -s -f _clinkgrammar.so.5.3.15 _clinkgrammar.so || { rm -f _clinkgrammar.so && ln -s _clinkgrammar.so.5.3.15 _clinkgrammar.so; }; })
libtool: install: /usr/bin/install -c .libs/_clinkgrammar.lai /linkgrammar/_clinkgrammar.la
libtool: install: /usr/bin/install -c .libs/_clinkgrammar.a /linkgrammar/_clinkgrammar.a
libtool: install: chmod 644 /linkgrammar/_clinkgrammar.a
libtool: install: ranlib /linkgrammar/_clinkgrammar.a
libtool: finish: PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/sbin" ldconfig -n /linkgrammar
----------------------------------------------------------------------
Libraries have been installed in:
   /linkgrammar

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the '-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the 'LD_RUN_PATH' environment variable
     during linking
   - use the '-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to '/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
 /bin/mkdir -p '/linkgrammar'
 /usr/bin/install -c -m 644 ../../bindings/python/linkgrammar.py ../../bindings/python3/__init__.py ../../bindings/python3/clinkgrammar.py '/linkgrammar'
Byte-compiling python modules...
linkgrammar.py__init__.pyclinkgrammar.py
Byte-compiling python modules (optimized versions) ...
linkgrammar.py__init__.pyclinkgrammar.py
make[1]: выход из каталога «/home/ubuntu/tmp/link-grammar-5.3.15/bindings/python3»
```
Here is one warning `libtool: warning: relinking '_clinkgrammar.la'`. I dont know, is it bad or normal.

After that I do:
```
cd ../python/examples
./example.py
```
And have next output:
```
$ ./example.py 
Traceback (most recent call last):
  File "./example.py", line 7, in <module>
    from linkgrammar import Sentence, ParseOptions, Dictionary, Clinkgrammar as clg
ImportError: No module named 'linkgrammar'
```

What is wrong?

**Comment by mnvx** [comment] 2017-03-31 15:08
Oh... Fixed by 
```
$ export PYTHONPATH=$PYTHONPATH:/linkgrammar
```

**Comment by linas** [comment] 2017-04-02 16:46
Well, there is still some sort of very strange bug with your installation.  The LG libraries are supposed to get installed in `/usr/local/lib` and the python code into `/usr/local/lib/python3.4/dist-packages/link-grammar`  -- these install paths do not require a special `PYTHONPATH` 

I'm guessing that the last three steps that you did:
```
cd bindings/python3
make
sudo make install
```

somehow caused the broken install. These last three steps are not needed or desired -- the python bindings should have been built and installed (in the correct locations) by the main build/install cycle.

**Comment by hosford42** [comment] 2017-08-18 23:32
@linas, I just stumbled across a very similar error -- minus the steps that you say caused the error. For Python 2.x, the module was installed correctly, but for Python 3.x, it turned out that the package was installed to `site-packages` rather than to `dist-packages`. Moving the files over to dist-packages fixed the issue. I'll try to submit a patch.

Also, while I have your attention, is there any support for installing to a virtual environment? I'm still new to Linux, so I apologize if this is something I ought to know from dealing with other Python packages.

**Comment by hosford42** [comment] 2017-08-19 00:00
I dig some digging and wanted to make sure what I found is documented for anyone else running into a similar problem. It turns out there is [a known bug in Ubuntu's python3 sysconfig package](https://bugs.launchpad.net/ubuntu/+source/python3-defaults/+bug/1408092) which is causing this.

**Comment by linas** [comment] 2017-08-25 04:46
I'm not a python expert, but it seems that in python2, the correct location was `site-packages`, which they eliminated in python3, replacing it with `dist-packages` (or maybe the other way around?). The result of this appears to mass confusion and a slew of bugs. I attempted to follow the official python documentation, and install to that place that python3 claims is correct (irrespective of how different distros might be altering the defaults).

I don't know what you mean by "virtual environment".  There must be many dozens of things that are "virtual environments" in Linux -- which one?

**Comment by szpak4** [comment] 2017-10-22 22:45
Has there been any progress on this matter? I have the same trouble with importing linkgrammar. I run Mac OS 10.13, so Unix rather than Linux, and Python 3.5.3. Installation of link-grammar-5.4.2 worked all right, but Mac does not have ldconfig. I ran sudo update_dyld_shared_cache instead as someone advised, with no change to the import error. I noted that the installation created /usr/local/lib/python2.7/ but there is nothing matching for Python 3. I copied linkgrammar.py to this directory, and that seems to have worked, but then clinkgrammar was missing. And so on.

Thanks in advance for any help!

**Comment by linas** [comment] 2017-10-23 02:18
Hi @szpak4  -- Python should have installed into  `/usr/local/lib/python3.5/site-packages/link-grammar` 

Perhaps they should be installed into  `/usr/local/lib/python3.5/dist-packages/link-grammar`   ??

Perhaps this might help:
```
export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python3.5/site-packages
```

**Comment by linas** [comment] 2017-10-23 02:26
Ahhh: @szpak4 you state:

> I noted that the installation created /usr/local/lib/python2.7/ but there is nothing matching for Python 3. 

This suggests that the python3 bindings were never actually created for you.  During the `configure` step, you should have seen this printed:
```
link-grammar-5.4.2  build configuration settings
...
	Python3 interfaces:             3.5
```
If you see a `no` there, that means that some python3 prerequisite is missing, most likely the python3 development header files (the python3 development environment). Install that, re-run configure; make; make install and it should now install something...

**Comment by szpak4** [comment] 2017-10-23 05:55
There is a "no" there. Configuring gives me (among lots of other lines) this:
checking whether "python" is Python3... no
checking for python3 version... 3.5
	Python2 interfaces:             2.7
	Python3 interfaces:             no
But: I find suggestions on the Web on installing development header files. Those suggestions call for a Homebrew installation of Python 3, which would mean 3.6. Now, 3.6 and NLTK (the reason I need all this) are not yet friends. I have 3.5 and NLTK talking to each other nicely, and I cannot upgrade to 3.6 now: teaching a course, not wishing to disrupt anything.

I realize I am asking more for Python advice than for Link Grammar advice, but I guess they add up to the same thing (-:). Thanks!

**Comment by ampli** [comment] 2017-10-23 07:15
Hi @szpak4,
For a solution see my post at issue #589.
See section 3 there about telling Homebrew to switch to python 3.5:
`brew switch python3 3.5.2_3`

**Comment by szpak4** [comment] 2017-10-23 12:12
FWIW, the default Python on my Mac also does not recognize Link Grammar. Like this:

Python 2.7.10 (default, Jul 15 2017, 17:16:57) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import linkgrammar
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named linkgrammar

Hmmmm.

**Comment by szpak4** [comment] 2017-10-23 13:03
ampli wrote: "For a solution see my post at issue #589." Thanks.

But: I followed all that, and even reinstalled python3 using brew. Still no progress. Neither 2.7 not 3.5 can see linkgrammar.

On the point of giving up...

**Comment by linas** [comment] 2017-10-23 13:48
@szpak4  Hang on. Last time, you reported that the import worked, but that the load of the clinkgrammar did not.  So you've slid backwards, somehow.  I'm somewhat concerned that by copying files manually, you've confused the system. You might want to make sure you didn't leave behind fragments from earlier attempts.

The only reason that the import fails is because `linkgrammar.py` is NOT in your `PYTHONPATH`.  So try fixing that first - it should be easy.  I am crossing my fingers that the missing clinkgrammar problem will also go away, if it doesn't, then use `DYLD_LIBRARY_PATH` . Between these two, the issue should resolve itself, but you have to be methodical to the point of being a little bit autistic about it all.

**Comment by szpak4** [comment] 2017-10-23 15:29
> Last time, you reported that the import worked, 

I cannot have. It has not worked once yet.

> The only reason that the import fails is because linkgrammar.py is NOT in your PYTHONPATH. 

PYTHONPATH in my system is empty. I just put on it the only directory where linkgrammar.pyc sits (but not linkpgrammar.py), which is /usr/local/lib/python2.7/site-packages/linkgrammar -- and again neither 2.7 not 3.5 recognize my request to import linkgrammar.

> you have to be methodical to the point of being a little bit autistic about it all.

Don't I know it. Perhaps I should uninstall Python 3 and Link Grammar and start afresh, assuming uninstalling is possible.

BTW, I used brew to install Python 3, and I now have 3.6 in the brew-selected place, 3.5 in Applications (which my Mac recognizes), and 2.7 baked into Mac OS.  But ampli's advice about "brew switch python3 3.5.2_3" will not work: no such version in the cellar.

Thanks... I hope it all resolves itself one way or another.

**Comment by linas** [comment] 2017-10-23 16:50
OK, well, up above, you wrote:

> and that seems to have worked, but then clinkgrammar was missing

which tells me that you did have it partly working at one point.  If you are methodical, perhaps you can return to that point.

I'm not sure what to say. What were you trying to accomplish? Programming in python is like playing the piano: anyone can do it, you just hit the keys, and sounds come out.  So you are hitting the keys, and sounds are coming out, but It seems that even if you got link-grammar to work, you would then promptly get stuck at the next stage.   Perhaps there is some alternate approach to what you are trying to do?

**Comment by szpak4** [comment] 2017-10-23 18:39
> OK, well, up above, you wrote:
>>  and that seems to have worked, but then clinkgrammar was missing

That was when I physically copied a file to another directory.

> If you are methodical, perhaps you can return to that point.

Uh. Well.

> I'm not sure what to say. What were you trying to accomplish? Programming in python is like playing the piano: anyone can do it, you just hit the keys, and sounds come out. 

I can program in Python, thanks.

> So you are hitting the keys, and sounds are coming out, but It seems that even if you got link-grammar to work, you would then promptly get stuck at the next stage. Perhaps there is some alternate approach to what you are trying to do?

Doubt it. I teach an NLP class using NLTK, and wanted to show my students how to use Link Grammar. So no alternate approach, if I want that to be done in Python.

**Comment by ampli** [comment] 2017-10-23 18:55
Hi @szpak4,
Don't give up, since I can ensure you that if you the "right" things the default system python (2.7.10) works fine out of the box when installing LG 5.4.2 on MacOS (at least on an up to date Sierra).

(For Homebrew, the matter is different, and some of their Python versions need a special care due to configuration bugs in them.)

To use the default system Python versions (2.7.10 and 3.5.2):

1) Verify that your python version is indeed the desired one:
`python -V`
(`configure` uses the first one that it finds in the PATH!)

2) `make uninstall` to lessen the chance of leftovers that will still be used.
3) `configure` and `make install`.

4) Note that with the system's python you must set PYTHONPATH.
```
$ export PYTHONPATH=/usr/local/lib/python2.7/site-packages
$ python
Python 2.7.10 (default, Feb  7 2017, 00:08:15) 
...
>>> import linkgrammar
>>>
```
(I made this test just now.)

To use the Homebrew's python-2 (2.7.14) you need to `brew install python` and then make sure
it is first in your PATH (you can verify that by `python -V`).  The installation commend notifies you the command to set the PATH.

Then repeat steps 2 and 3.
In step 4 there is no need to set the PYTHONPATH in that case, since the installed place is used by that python version by default. I also tested that just now.

Here is the result, with actual usage example to check that the library itself is in working condition:
```
$ python
Python 2.7.14 (default, Sep 25 2017, 09:53:22) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from linkgrammar import *
>>> print(Sentence("This is a test",Dictionary(),ParseOptions()).parse().next().diagram())

    +----->WV----->+---Ost--+
    +---Wd---+-Ss*b+  +Ds**c+
    |        |     |  |     |
LEFT-WALL this.p is.v a  test.n 


>>> 
```

[With Homebrew's python 3.5 there was a problem that I fixed (and sent them a patch, which they promptly applied). However, they don't distribute this version any more, but 3.6, which has another problem that prevents its proper linking (I guess I will also have to send a fix).]

**Comment by szpak4** [comment] 2017-10-24 05:14
> Don't give up, since I can ensure you that if you the "right" things the default system python (2.7.10) works fine out of the box when installing LG 5.4.2 on MacOS (at least on an up to date Sierra). [...]

Great advice. Thanks!!!

**Comment by ashengtx** [comment] 2018-05-23 09:16
@linas  my system (Ubuntu 16), python libraries are installed in `/usr/local/lib/python3.5/dist-packages/` for python3 and in `/usr/local/lib/python2.7/dist-packages/` for python2. Both of them are `dist-packages`, not `site-packages`. However, in the files about `configure` and `make`, the default settings for python3 are `site-packages`, which causes that the `linkgrammar` is installed in the wrong place and python3 interpreter can't find it. 

I tried to fixed this by replacing the `site-packages` in all files with `dist-packages`, and then execute `sudo make install`. Finally it works! 

Curiousely, I found that in Windows the path to packages is 'site-packages' for python3 which is different from that in Unbuntu. I hope in the later version this problem will be fixed. Thanks!

**Comment by linas** [comment] 2018-05-23 17:06
Hi @ashengtx we are trying to follow the official Python documentation. The dist-packages directory is for packages that come with the distro, the site-packages directory is for packages installed on-site. Python should be able to find both directories just fine.  Verify that your Python configuration checks both directories, instead of ignoring one or the other.

**Comment by hosford42** [comment] 2018-05-23 20:50
It is the same for my setup, also on Ubuntu 16.04. Python does not appear
to check both.

**Comment by linas** [comment] 2018-05-23 21:58
Argh.  Stackoverflow about site and dist:  https://stackoverflow.com/questions/9387928/whats-the-difference-between-dist-packages-and-site-packages  -- apparently, ubuntu and debian want dist, everyone else want site. 

However, AM_PATH_PYTHON  https://www.gnu.org/software/automake/manual/html_node/Python.html always returns site, even for debian/ubnutu.  The current configure.ac uses AM_PATH_PYTHON, so this is broken.

But apparently, its broken because python itself is reporting the wrong location for debian/ubuntu: `python3 -m sysconfig` prints, on debian stable:
```
Paths: 
	data = "/usr"
	include = "/usr/include/python3.5m"
	platinclude = "/usr/include/python3.5m"
	platlib = "/usr/lib/python3.5/site-packages"
	platstdlib = "/usr/lib/python3.5"
	purelib = "/usr/lib/python3.5/site-packages"
```
The above is apparently a well-known bug, that still has not been fixed: https://bugs.launchpad.net/ubuntu/+source/python3-defaults/+bug/1408092

I'll attempt to do some debian/ubuntu over-ride in the configure file.

**Comment by MarkMMullin** [comment] 2018-06-22 23:36
I just ran into this problem on a mac running high sierra 10.13.5  with link-grammar-5.5.0 
I use anaconda          
conda version : 4.5.4
conda-build version : 1.18.2
python version : 3.5.5.final.0

The issue is that the linkgrammar stuff doesn't appear in the anaconda environments, only in the system python directories - /usr/local/lib/python3.5/site-packages in my case

I'm not going to fault the library folk for this, until they're an anaconda distribution they've implied they don't care, and it would be an awful mess if they tried -  which envs would they update ?

The cure is very simple

Go to /usr/local/lib/python3.5/site-packages - you should see linkgrammar  and linkgrammar.pth there, or something else has gone wrong.

Now do

cp -r * ~/anaconda/envs/<ANACONDA_ENV>/site-packages/ for every environment you want to be able to use the link grammar

This is a little wasteful, one could get quite fancy with links and whatnot but I figure disk storage is cheaper than the time that would take me.  Anyone else is welcome :-)

To test

in a console

source activate <ANACONDA_ENV>
python
from linkgrammar import *
print(Sentence("This is a test",Dictionary(),ParseOptions()).parse().next().diagram())

You should get

    +----->WV----->+---Osm--+
    +-->Wd---+-Ss*b+  +Ds**c+
    |        |     |  |     |
LEFT-WALL this.p is.v a  test.n

**Comment by linas** [comment] 2018-06-22 23:46
Someone recently remarked to me that they want to/plan to create anaconda packages for link-grammar.  They made it sound like  it would get done in a few weeks or a month.

**Comment by MarkMMullin** [comment] 2018-06-23 10:53
It would be a good thing given what moves in conda packages -  didn't seem that hard, as it was purely distributing what got built to the right places -  links would be better than my lazy approach, the only rub I'd see is picking the envs linkgrammar gets put into

**Comment by linas** [comment] 2021-02-09 05:00
I'm closing this as stale/old. If you are reading this, and have ongoing issues/bugs, please open a new bug report.

If you are an anaconda maintainer, please help out! The above shoots over my head!

**Closed by linas** 2021-02-09 05:00 UTC
Labels: python

**Comment by Antipire** [comment] 2021-10-16 13:22
Using ubuntu 18.04, python3.6, link-grammar-4.7.12. Same problem. After `./configure`, `make install` and so on, this error appears `ModuleNotFoundError: No module named 'linkgrammar'`. Spent a lot of time trying to solve and found that linkgrammar isn't installed in python `dist-packages` folder. Last version (5.10) is making errors while trying to `sudo make` in `tests.py`, so that why I'm using old version.

**Comment by Antipire** [comment] 2021-10-16 13:49
@Antipire for my last message
I fixed problem with module by simply `sudo apt-get install python3-link-grammar`, but right now Im struggling with russian dictionary: `link-grammar: Info: Dictionary 'ru/4.0.dict': No locale definition - "en_US.UTF-8" will be used.`, but I literally see in `data` folder ru dictionary.

**Comment by linas** [comment] 2021-10-30 04:28
Hi @Antipire  Sorry for the late reply. I think the Russian thing is you don't have the russian locales installed on your ubuntu box. This has nothing to do with link-grammar, its linux-distro generic.

You'd have to search to the exact instructions, but it involves running `update-locale` or `localedef` or a similar program, and installing the russian locale.  If I recall, it will give you a list of hundreds of locales, from A to Z, and scroll down to `RU_ru` and select that.  it will rebuild the local file (about a minute or two for each locale) Careful not to select all -- it will write many gigabytes of stuff into `/usr` and wipe out your free disk space.
