### ISSUE TITLE
Debian warning about symbols "found in none of the libraries"

### ISSUE THREAD

**Issue by jbicha** [opencog/link-grammar#428] opened 2016-09-28 23:15 UTC
When I build link-grammar on Debian, I get these warnings:
```
dpkg-shlibdeps: warning: symbol _ZNSt8ios_base4InitC1Ev used by debian/liblink-grammar5/usr/lib/x86_64-linux-gnu/liblink-grammar.so.5.3.11 found in none of the libraries
dpkg-shlibdeps: warning: symbol _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE14_M_replace_auxEmmmc used by debian/liblink-grammar5/usr/lib/x86_64-linux-gnu/liblink-grammar.so.5.3.11 found in none of the libraries
dpkg-shlibdeps: warning: symbol _ZNSolsEi used by debian/liblink-grammar5/usr/lib/x86_64-linux-gnu/liblink-grammar.so.5.3.11 found in none of the libraries
```
etc.  [Full build log](https://buildd.debian.org/status/fetch.php?pkg=link-grammar&arch=amd64&ver=5.3.11-1&stamp=1475069679)

When I looked into this, it has something to do with link-grammar building with minisat but not linking correctly with lstdc++

It looks like adding this to _configure.ac_ fixes the problem:
`AC_CHECK_LIB(stdc++, main)`

So I wonder if that can replace the `We want to check for C++; the easiest way to do this is to use c++ to compile stdio.h and bomb if it fails.` section:
https://github.com/opencog/link-grammar/blob/master/configure.ac#L286

**Comment by ampli** [comment] 2016-10-01 02:42
It seems to me that the heuristics used by `dh_shlibdeps` (or something) have a problem:
```
$ ldd debian/liblink-grammar5/usr/lib/x86_64-linux-gnu/liblink-grammar.so.5.3.11
	linux-vdso.so.1 (0x00007fff190eb000)
	libhunspell-1.4.so.0 => /usr/lib/x86_64-linux-gnu/libhunspell-1.4.so.0 (0x00007f9e66f76000)
	libminisat.so.2 => /usr/lib/libminisat.so.2 (0x00007f9e66d62000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f9e66b45000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f9e66841000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f9e6662a000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9e6628a000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f9e65
...
```
Note the libstdc++.so.6 line. The "missing" symbol is there:
```
$ nm -D /usr/lib/x86_64-linux-gnu/libstdc++.so.6| grep _ZNSt8ios_base4InitD1Ev
000000000009fd90 T _ZNSt8ios_base4InitD1Ev
```
So it seems to me `dh_shlibdeps` just doesn't know for some reason that `libstdc++.so.6` is one of the libraries used by  `liblink-grammar.so.5.3.11`. It can be interesting to find out the reason.
I guess that adding `AC_CHECK_LIB(stdc++, main)` tells it so. It looks as if it just a harmless noop so I think it can be added if the reason for the library detection problem of `dh_shlibdeps`  cannot be found. 


BTW, in the rule file there is:
```
override_dh_makeshlibs:
# A private C++ library
        dh_makeshlibs -Xlibminisat
```
But libminisat is not a private C library any more.

And also:
```
override_dh_auto_configure:
        dh_auto_configure -- \
                --disable-static \
                --enable-pthreads \
                --enable-python-bindings
```
Is there a reason for using --enable-pthreads?

**Comment by jbicha** [comment] 2016-10-01 03:05
> override_dh_makeshlibs:

Yes, I corrected that [rule](https://anonscm.debian.org/cgit/collab-maint/link-grammar.git/tree/debian/rules) -- I just haven't pushed a new package yet. But I still get the warning when building with that corrected.

> Is there a reason for using --enable-pthreads?

Honestly I copied it from [Fedora](http://pkgs.fedoraproject.org/cgit/rpms/link-grammar.git/tree/link-grammar.spec#n63).

**Comment by ampli** [comment] 2016-10-01 16:03
It turns out these warnings are not due to a problem in `dh_shlibdeps`.
The problem is that link-grammar solib doesn't actually depend on `libstdc++`, but it contains symbols from it.

The reason that `ldd` on `liblink-grammar.so.5.3.11` shows `libstdc++` is because it scans the dependencies recursively, and actually finds `libstdc++` as a dependency of libminisat.so.2. This is the thing that `dh_shlibdeps` would like to eliminate, namely libraries that have their dependencies resolved through other libraries (it is considered to cause symbol-resolution slowness and introduces indirect  dependencies that may disappear).

So adding `AC_CHECK_LIB(stdc++, main)` as you suggest is needed for all the systems that use it (on OS X it is not used, and LDFLAGS there already includes the needed C++ library).

I did so and will send a PR. (It is currently added only if sat-solver is enabled, because this is the only C++ source for now.)

BTW, I noted that the Debian build has several other warnings, whose reason and severity I don't know,
like the following:
```
libtool: warning: remember to run 'libtool --finish /usr/lib/x86_64-linux-gnu'```
...
dpkg-gencontrol: warning: Depends field of package liblink-grammar-dev: unknown substitution variable ${shlibs:Depends}
dpkg-gencontrol: warning: package python-link-grammar: unused substitution variable ${python:Versions}
```

**Comment by ampli** [comment] 2016-10-03 21:32
I'm closing this, since commit [--enable_sat-solver: Link the link-grammar solib with libstdc++](https://github.com/opencog/link-grammar/pull/429/commits/78b396b31f21a205db7b42bcaaa077cc4584afba) of PR #429 is supposed to fix this problem. Please reopen if the problem persists or it causes another problem.

**Closed by ampli** 2016-10-03 21:32 UTC
